name: qr_scan
description: Wallet Connect QR Scan
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # functional dependencies
  walletconnect_flutter_v2: ^2.1.4

  # api
  # dio: ^5.3.2

  #state management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # di and code generator
  get_it: ^7.2.0
  injectable: ^1.5.3
  retrofit: ^4.0.1

  #animations and ui
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^4.0.5
  avatar_glow: ^2.0.2
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  flare_flutter: ^3.0.0-nullsafety.1


  flutter_vibrate: ^1.0.0

  #qr code
  scan: ^1.6.0
  qr_code_scanner: ^1.0.1
  file_picker: ^5.2.4
  # modal_bottom_sheet: ^3.0.0-pre
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  injectable_generator: ^1.5.4
  json_serializable: ">4.4.0"
  # retrofit_generator: ">=5.0.0 <6.0.0"
  build_runner: ">=2.3.0 <4.0.0"
  test: ^1.16.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

